# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{activerecord_vertica_adapter}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Jerome Riga}]
  s.date = %q{2012-03-21}
  s.description = %q{ActiveRecord adapter for Vertica databaes}
  s.email = %q{jriga@zemis.co.uk}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "activerecord_vertica_adapter.gemspec",
    "lib/active_record/connection_adapters/vertica_adapter.rb",
    "test/helper.rb",
    "test/test_activerecord_vertica_adapter.rb"
  ]
  s.homepage = %q{http://github.com/zemis/activerecord_vertica_adapter}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{ActiveRecord adapter for Vertica database}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, ["~> 3.x.x"])
      s.add_runtime_dependency(%q<vertica>, ["~> 0.9.x"])
      s.add_development_dependency(%q<yard>, "~> 0.9.20")
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, ["~> 3.x.x"])
      s.add_dependency(%q<vertica>, ["~> 0.9.x"])
      s.add_dependency(%q<yard>, "~> 0.9.20")
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, ["~> 3.x.x"])
    s.add_dependency(%q<vertica>, ["~> 0.9.x"])
    s.add_dependency(%q<yard>, "~> 0.9.20")
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

